---
title: "Oppgave 1"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Task 1a)

* We see that for K=1, the variance is pretty high, which is expected as the curves only will go from point to point. At K=2 we see that the variance lowers some as we now take in to account the two nearest points, and the peaks will not be that far away from the true line. When K increases, we take account for neigbhours which is not necessary very local anymore. Which K to choose to keep the neighbourhood local depends on the number of observations in the trainingset, and here n=61, and already when K=10, we get somewhat of a problem in the end points. Although a very good fit along most of the line, at the end, it will take the same points in account, and one will get a straight line. At K=61, one will get a straight line, which is the mean.

* A small value of K will give a more flexible fit, which has low bias but high variance. As mentioned above, K=1 will give point-to-point plots, which is an overfit. At K=2 we get a lower variance, and there is no sign of underfitting the curve. At K=10 the variance is notably lower, but the plot shows signs of underfitting and a low flexibility. Continuing the trend, at K=25 we get clearly a underfit and to low flexibility.

* The MSE fot the training sets shows how close the predicted curve is to the points it is based on. As we can see, at K=1 the MSE is zero, which is a clear sign of overfitting. The MSE just increase as K increases, which indicates low flexibility. There is by this plot hard to say where the overfitting stops and the low flexibility starts, and thus hard to conclude what's the best value for K. 
One the other hand, the MSE for the test sets does decrease for the first K's, and then increases. The test set isn't affected by overfitting the same way, and will therefor show the best value for K much clearer. 

* The lowest point, being around K=5 here, is where the error is lowest and would be our choice for K. $\epsilon$